from datetime import datetime
from sqlalchemy import String,Text,Integer,DateTime,ForeignKey,Float,Boolean,UniqueConstraint,JSON
from sqlalchemy.orm import Mapped,mapped_column,relationship
from .db import Base
class User(Base):
 __tablename__='users'; id:Mapped[int]=mapped_column(primary_key=True); username:Mapped[str]=mapped_column(String(100),unique=True,index=True); password_hash:Mapped[str]=mapped_column(String(255)); role:Mapped[str]=mapped_column(String(30),default='admin'); disabled:Mapped[bool]=mapped_column(Boolean,default=False); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Target(Base):
 __tablename__='targets'; id:Mapped[int]=mapped_column(primary_key=True); root:Mapped[str]=mapped_column(String(255),unique=True,index=True); enabled:Mapped[bool]=mapped_column(Boolean,default=True); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
 scopes:Mapped[list['Scope']]=relationship('Scope',back_populates='target',foreign_keys='Scope.target_id',cascade='all, delete-orphan')
 scans:Mapped[list['Scan']]=relationship('Scan',back_populates='target',foreign_keys='Scan.target_id')
class Scope(Base):
 __tablename__='scopes'; id:Mapped[int]=mapped_column(primary_key=True); target_id:Mapped[int]=mapped_column(ForeignKey('targets.id')); include:Mapped[str]=mapped_column(Text); exclude:Mapped[str]=mapped_column(Text,default=''); excluded_paths:Mapped[str]=mapped_column(Text,default=''); max_rps:Mapped[float]=mapped_column(Float,default=1); concurrency:Mapped[int]=mapped_column(Integer,default=1); stage_cooldown:Mapped[int]=mapped_column(Integer,default=240); profile:Mapped[str]=mapped_column(String(30),default='safe'); authorization_confirmed:Mapped[bool]=mapped_column(Boolean,default=False); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
 target:Mapped['Target']=relationship('Target',back_populates='scopes',foreign_keys=[target_id])
class Scan(Base):
 __tablename__='scans'; id:Mapped[int]=mapped_column(primary_key=True); target_id:Mapped[int]=mapped_column(ForeignKey('targets.id')); scope_id:Mapped[int]=mapped_column(ForeignKey('scopes.id')); profile:Mapped[str]=mapped_column(String(30),default='safe'); status:Mapped[str]=mapped_column(String(30),default='QUEUED'); progress:Mapped[int]=mapped_column(Integer,default=0); current_stage:Mapped[str]=mapped_column(String(100),default='Queued'); current_tool:Mapped[str]=mapped_column(String(100),default=''); cancel_requested:Mapped[bool]=mapped_column(Boolean,default=False); pause_requested:Mapped[bool]=mapped_column(Boolean,default=False); started_at:Mapped[datetime|None]=mapped_column(DateTime); finished_at:Mapped[datetime|None]=mapped_column(DateTime); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); updated_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
 target:Mapped['Target']=relationship('Target',back_populates='scans',foreign_keys=[target_id],lazy='joined')
 scope:Mapped['Scope']=relationship('Scope',foreign_keys=[scope_id],lazy='joined')
class Asset(Base):
 __tablename__='assets'; __table_args__=(UniqueConstraint('scan_id','hostname',name='uq_asset_scan_host'),); id:Mapped[int]=mapped_column(primary_key=True); scan_id:Mapped[int]=mapped_column(ForeignKey('scans.id')); hostname:Mapped[str]=mapped_column(String(255),index=True); canonical:Mapped[str]=mapped_column(String(255)); status:Mapped[str]=mapped_column(String(30),default='UNKNOWN'); source:Mapped[str]=mapped_column(Text,default=''); ips:Mapped[str]=mapped_column(Text,default=''); ports:Mapped[str]=mapped_column(Text,default='')
class DNSRecord(Base):
 __tablename__='dns_records'; id:Mapped[int]=mapped_column(primary_key=True); scan_id:Mapped[int]=mapped_column(ForeignKey('scans.id')); hostname:Mapped[str]=mapped_column(String(255)); rtype:Mapped[str]=mapped_column(String(20)); value:Mapped[str]=mapped_column(Text); source:Mapped[str]=mapped_column(String(100),default='dig')
class HTTPService(Base):
 __tablename__='http_services'; id:Mapped[int]=mapped_column(primary_key=True); scan_id:Mapped[int]=mapped_column(ForeignKey('scans.id')); url:Mapped[str]=mapped_column(Text); hostname:Mapped[str]=mapped_column(String(255)); port:Mapped[int|None]=mapped_column(Integer); scheme:Mapped[str]=mapped_column(String(10)); status_code:Mapped[int|None]=mapped_column(Integer); title:Mapped[str]=mapped_column(Text,default=''); content_type:Mapped[str]=mapped_column(Text,default=''); server:Mapped[str]=mapped_column(Text,default=''); technologies:Mapped[str]=mapped_column(Text,default=''); redirect_chain:Mapped[str]=mapped_column(Text,default='')
class Technology(Base):
 __tablename__='technologies'; id:Mapped[int]=mapped_column(primary_key=True); scan_id:Mapped[int]=mapped_column(ForeignKey('scans.id')); hostname:Mapped[str]=mapped_column(String(255)); name:Mapped[str]=mapped_column(String(255)); version:Mapped[str]=mapped_column(String(100),default=''); confidence:Mapped[str]=mapped_column(String(30),default='MEDIUM'); source:Mapped[str]=mapped_column(String(100))
class URL(Base):
 __tablename__='urls'; id:Mapped[int]=mapped_column(primary_key=True); scan_id:Mapped[int]=mapped_column(ForeignKey('scans.id')); url:Mapped[str]=mapped_column(Text); kind:Mapped[str]=mapped_column(String(30),default='UNKNOWN'); source:Mapped[str]=mapped_column(String(100)); status_code:Mapped[int|None]=mapped_column(Integer)
class Endpoint(Base):
 __tablename__='endpoints'; id:Mapped[int]=mapped_column(primary_key=True); scan_id:Mapped[int]=mapped_column(ForeignKey('scans.id')); url:Mapped[str]=mapped_column(Text); path:Mapped[str]=mapped_column(Text); kind:Mapped[str]=mapped_column(String(30),default='UNKNOWN'); parameters:Mapped[str]=mapped_column(Text,default='')
class Finding(Base):
 __tablename__='findings'; __table_args__=(UniqueConstraint('scan_id','fingerprint',name='uq_finding_fp'),); id:Mapped[int]=mapped_column(primary_key=True); scan_id:Mapped[int]=mapped_column(ForeignKey('scans.id')); title:Mapped[str]=mapped_column(String(500)); severity:Mapped[str]=mapped_column(String(30),default='INFO'); url:Mapped[str]=mapped_column(Text,default=''); parameter:Mapped[str]=mapped_column(Text,default=''); evidence:Mapped[str]=mapped_column(Text,default=''); source:Mapped[str]=mapped_column(String(200),default='automated'); confidence:Mapped[str]=mapped_column(String(30),default='MEDIUM'); verification:Mapped[str]=mapped_column(String(50),default='UNVERIFIED'); fingerprint:Mapped[str]=mapped_column(String(64)); first_seen:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); last_seen:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Evidence(Base):
 __tablename__='evidence'; id:Mapped[int]=mapped_column(primary_key=True); finding_id:Mapped[int]=mapped_column(ForeignKey('findings.id')); http_status:Mapped[int|None]=mapped_column(Integer); headers:Mapped[str]=mapped_column(Text,default=''); metadata_json:Mapped[dict]=mapped_column(JSON,default=dict); scanner_output:Mapped[str]=mapped_column(Text,default=''); captured_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class ToolRun(Base):
 __tablename__='tool_runs'; id:Mapped[int]=mapped_column(primary_key=True); scan_id:Mapped[int]=mapped_column(ForeignKey('scans.id')); tool:Mapped[str]=mapped_column(String(100)); stage:Mapped[str]=mapped_column(String(100)); status:Mapped[str]=mapped_column(String(30)); command_display:Mapped[str]=mapped_column(Text,default=''); exit_code:Mapped[int|None]=mapped_column(Integer); output:Mapped[str]=mapped_column(Text,default=''); error:Mapped[str]=mapped_column(Text,default=''); started_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); finished_at:Mapped[datetime|None]=mapped_column(DateTime)
class Log(Base):
 __tablename__='logs'; id:Mapped[int]=mapped_column(primary_key=True); scan_id:Mapped[int]=mapped_column(ForeignKey('scans.id')); level:Mapped[str]=mapped_column(String(20),default='INFO'); message:Mapped[str]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Report(Base):
 __tablename__='reports'; id:Mapped[int]=mapped_column(primary_key=True); scan_id:Mapped[int]=mapped_column(ForeignKey('scans.id')); fmt:Mapped[str]=mapped_column(String(20)); path:Mapped[str]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Schedule(Base):
 __tablename__='schedules'; id:Mapped[int]=mapped_column(primary_key=True); target_id:Mapped[int]=mapped_column(ForeignKey('targets.id')); scope_id:Mapped[int]=mapped_column(ForeignKey('scopes.id')); frequency_minutes:Mapped[int]=mapped_column(Integer,default=1440); enabled:Mapped[bool]=mapped_column(Boolean,default=True); next_run:Mapped[datetime]=mapped_column(DateTime); last_run:Mapped[datetime|None]=mapped_column(DateTime); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class AuditLog(Base):
 __tablename__='audit_logs'; id:Mapped[int]=mapped_column(primary_key=True); username:Mapped[str]=mapped_column(String(100)); action:Mapped[str]=mapped_column(String(100)); details:Mapped[str]=mapped_column(Text,default=''); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
